services:
  app:
    env_file: .env
    build: .
    image: partywiki
    # command: python manage.py runserver 0.0.0.0:${CONTAINER_PORT}
    # command: gunicorn -c config/gunicorn_config.py config.wsgi --bind 0.0.0.0:${CONTAINER_PORT}
    volumes:
      - .:/code
      - partywiki_logs:/var/log
    ports:
      - "127.0.0.1:${CONTAINER_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:${CONTAINER_PORT}/health-check/" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  cron:
    env_file: .env
    image: partywiki
    init: true
    command: bash -c "crontab /code/crontab.txt && crond -f"
    volumes:
      - .:/code
    depends_on:
      - app
    restart: unless-stopped

volumes:
  partywiki_logs:
    driver: local
