version: '2'

services:
  app:
    env_file: .env
    container_name: partywiki_app
    build: .
    # command: python manage.py runserver 0.0.0.0:${CONTAINER_PORT}
    # command: gunicorn -c config/gunicorn_config.py config.wsgi
    volumes:
      - .:/code
      - partywiki_logs:/var/log
    depends_on:
      - postgres
    ports:
      - "${CONTAINER_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped

  cron:
    container_name: partywiki_app_cron
    build: .
    command: [ "/usr/sbin/crond", "-f" ]
    volumes:
      - .:/code
    depends_on:
      - app
    restart: unless-stopped

  postgres:
    env_file: .db-env
    image: postgres:14.5-alpine
    container_name: partywiki_postgres
    ports:
      - "5432:5432/tcp"
    volumes:
      - partywiki-db-data:/var/lib/postgresql/data
      - partywiki_logs:/var/log
    environment:
      TZ: "Europe/Helsinki"
    command: ["-c", "logging_collector=on", "-c", "log_directory=/var/log/", "-c", "log_filename=postgres.log"]
    restart: unless-stopped

volumes:
  partywiki-db-data:
    driver: local
  partywiki_logs:
    driver: local
