services:
  app:
    env_file: .env
    build: .
    # command: python manage.py runserver 0.0.0.0:${CONTAINER_PORT}
    # command: gunicorn -c config/gunicorn_config.py config.wsgi --bind 0.0.0.0:${CONTAINER_PORT}
    volumes:
      - .:/code
      - partywiki_logs:/var/log
    ports:
      - "127.0.0.1:${CONTAINER_PORT}:${CONTAINER_PORT}"
    restart: unless-stopped

  cron:
    build: .
    command: [ "/usr/sbin/crond", "-f" ]
    volumes:
      - .:/code
    depends_on:
      - app
    restart: unless-stopped

volumes:
  partywiki_logs:
    driver: local
