# Generated by Django 3.1.7 on 2021-02-27 17:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('iata_code', models.CharField(max_length=3)),
                ('country', django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=64)),
                ('departure_town', models.CharField(max_length=64)),
                ('departure_datetime', models.DateTimeField()),
                ('arrival_town', models.CharField(max_length=64)),
                ('arrival_datetime', models.DateTimeField()),
                ('detail1', models.CharField(blank=True, max_length=32, null=True)),
                ('detail2', models.CharField(blank=True, max_length=32, null=True)),
                ('towards_home', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='party.party')),
            ],
        ),
    ]
