# Generated by Django 3.1.7 on 2021-02-27 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0002_airport_trip'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('ship', 'Boat'), ('bus', 'Bus'), ('car', 'Car'), ('motorcycle', 'Motorcycle'), ('plane', 'Plane'), ('rocket', 'Rocket'), ('space-shuttle', 'Space Shuttle'), ('train', 'Train')], default='plane', max_length=13),
        ),
    ]
