# Generated by Django 3.1.7 on 2021-04-09 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('party', '0002_auto_20210409_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='user',
        ),
        migrations.AlterField(
            model_name='trip',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('ship', 'Boat'), ('bus', 'Bus'), ('car', 'Car'), ('motorcycle', 'Motorcycle'), ('plane', 'Plane'), ('train', 'Train'), ('other', 'Other')], default='plane', max_length=13),
        ),
    ]
