# Generated by Django 3.1.7 on 2021-03-03 22:54

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='arrival_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
        migrations.AddField(
            model_name='trip',
            name='departure_country',
            field=django_countries.fields.CountryField(blank=True, max_length=2),
        ),
    ]
