# Generated by Django 3.1.7 on 2022-03-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0003_auto_20210409_1935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='towards_home',
        ),
        migrations.AddField(
            model_name='trip',
            name='towards_party',
            field=models.BooleanField(default=True),
        ),
    ]
