# Generated by Django 3.1.7 on 2022-03-23 13:11

from django.db import migrations
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0005_auto_20220323_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='slug',
            field=django_extensions.db.fields.AutoSlugField(blank=True, editable=False, populate_from=['name', 'date_start__year']),
        ),
    ]
