# Generated by Django 3.1.7 on 2022-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0006_auto_20220323_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='type',
            field=models.CharField(choices=[('bicycle', 'Bicycle'), ('ship', 'Boat'), ('bus', 'Bus'), ('car', 'Car'), ('motorcycle', 'Motorcycle'), ('plane', 'Plane'), ('train', 'Train'), ('other', 'Other')], default='plane', max_length=13),
        ),
    ]
