# Generated by Django 4.1.2 on 2022-11-03 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0008_alter_party_id_alter_trip_id_alter_trip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
