# Generated by Django 4.2.3 on 2023-07-27 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0009_party_visible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='location',
            field=models.CharField(max_length=128),
        ),
    ]
