# Generated by Django 4.2.17 on 2024-12-09 06:18

from django.db import migrations
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('party', '0010_alter_party_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'get_latest_by': 'modified'},
        ),
        migrations.AddField(
            model_name='trip',
            name='created',
            field=django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='modified',
            field=django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified'),
        ),
    ]
